site_name: Equinor Terraform Baseline
site_description: ""
site_author: Cyclops team
site_url: https://equinor.github.io/terraform-baseline

repo_name: equinor/terraform-baseline
repo_url: https://github.com/equinor/terraform-baseline

copyright: Copyright &copy; 2023 Equinor

theme:
  name: material
  features:
    - navigation.instant # Make MkDocs behave like a Single Page Application (SPA).
    - navigation.tabs # Enables navigational tabs at top of page.
    - navigation.indexes # Enables use of "index.md" pages.
    - navigation.top # Enables "back-to-top" button.

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.highlight # Enable syntax highlighting of code blocks.
  - pymdownx.superfences # Enable arbitrary nesting of code and content blocks inside each other.
  - attr_list # Open links in new tabs by using syntax [<text>](<url>){target=_blank}.

nav:
  - Home:
      - index.md
  - Best Practices:
      - best-practices/index.md
  - Module Library:
      - module-library/index.md
