name: deploy

on:
  push:
    branches: [main]
    paths:
      - docs/**
      - mkdocs.yml

jobs:
  deploy:
    uses: equinor/ops-actions/.github/workflows/mkdocs-gh-pages.yml@main
    with:
      mkdocs_version: ">=1.0.0"
      python_version: "3.x"
